apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: tomlui2010/pawsandclaws-backend-app:1.0
        ports:
          - containerPort: 5000
        env:
          - name: DATABASE
            value: postgres
        envFrom:
          - configMapRef:
            name: templates-config
        volumeMounts:
          - name: templates-volume
            mountPath: /app/backend/templates
          - name: uploads-volume
            mountPath: /app/uploads
      restartPolicy: Always
              
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: templates-volume
          configMap:
            name: templates-config
            items:
              - key: index.html
                path: index.html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /data/uploads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi