version: 2.1

Parameters:
  clustername:
    Type: String
    Description: Name of the EKS cluster
jobs:
  create-cluster:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar and gzip
          command: |
            yum update -y
            yum install -y tar gzip
            yum install -y jq
      - run:
          name: Create EKS cluster
          command: |
             set +e
              aws cloudformation deploy \
                --template-file .circleci/files/ekscluster.yml \
                --stack-name "pawsandclaws-${CIRCLE_WORKFLOW_ID:0:7}" \
                --capabilities CAPABILITY_NAMED_IAM \
                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
                                    ClusterName=my-eks-cluster \
                                    VpcId=vpc-019cf5cbe4050e490 \
                                    SubnetIds="subnet-0b568a245265bb23c,subnet-0098d854d386263fa" \
                                    KeyName=pawsandclawskeypair \
                                    NodeGroupName=my-node-group \
                                    NodeInstanceType=t2.micro \
                                    DesiredCapacity=2 \
                --tags project=pawsandclaws
             DEPLOY_EXIT_CODE=$?
             if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
              aws cloudformation describe-stack-events --stack-name "pawsandclaws-${CIRCLE_WORKFLOW_ID:0:7}" >> /tmp/output.txt
              cat /tmp/backend-output.txt
              exit 1
             fi
             set -e
workflows:
  deployment:
    jobs:
      - create-cluster:
          context:
            - ppp